# Avoid ruby stuff
language: c
sudo: false

branches:
    only:
      - master

env:
  global:
    - INPUT_FILE=Slides.md
    - OUTPUT_FILE=index.html
    - GH_REPO=ivan-m/LambdaJam-Parsing
    - GH_BRANCH=gh-pages
    - secure: "kSS1z3IXea+s38rJRD/y7TRECIx7dt+9w8Bv/avaYIsJ0nSH/YxSLJKnvhxGMpHI5AMgJrwFdg/3JalZtCOkZutEaymHnedQatTuThPNEhIMjr5vzOeTQ8VSC1TRPOVjb72oaH8/UCRqGsj+0gKQ5mQ3O/4oCH7Xv97X3MqYEJnfImv/xA5I2Dv48u5vqi8YdV4dsXfxjqvUBo2BkI/H49Bu6U+xr9Su1/dqPYD2HuU5qPyswMn0SHLqWhbdLTxdAvJf1je3AveAGJp6PXtPyUEdA8XDVsRepQIwWVzlm2eKiVsit010D2BxSnbE/8o+ekfY+eu5OZ6xpOaUjcWETtSeFg/Q2vryIUFpNI3JRv+Np8ce8UecAGuc5k6xWFKx2DZ9/LxmgVN2NXv4dgvG94MwOy2mArHygpKBDPlFYLJTjSemsqIYp2P/eT2D5C4sexQvRx/csrqfNIqijUmo/ZWzakEWnXK1t1Wz1J1XPhaFyTEyex4kmBtTYy8sH2ohcOMONExl0LJ6zARYHz8mYhBo2SmRBXa3aCRSeRbynk/NBPOTSmGb6Pb7zzPut0/SZQ/32rCLwGQ4O1h7JGZZ1lzF5aYzcuzoVaJs5xOol0SmfdKqk33u3IyNKuac9Wfnojkn6l+pG9btmElp+I+JVC13Udvjl9gyWICsWp1fyCM="

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

before-cache:
  # Don't cache the Hackage index
  - rm -rf $HOME/.cabal/packages/hackage.haskell.org

branches:
  only:
    - master

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-2.2
      - ghc-8.4.2

before_install:
  - export PATH=$HOME/.cabal/bin:$(printf "%s:" /opt/ghc/*/bin)$(printf "%s:" /opt/cabal/*/bin)$PATH
  - travis_retry cabal update
  - travis_retry cabal install -j pandoc

script:
  - ./runPandoc.hs "${INPUT_FILE}" "${OUTPUT_FILE}"
  - git config --global user.email "Travis CI"
  - git config --global user.name "travis-ci@travis.org"
  - git clone --quiet --branch=$GH_BRANCH https://${GH_TOKEN}@github.com/$GH_REPO travis-build > /dev/null
  - cd travis-build
  # In case there's more images, etc.
  - git rebase origin/shared-data
  - cp ../"${OUTPUT_FILE}" .
  - git add -f .
  - git diff --cached --exit-code ||
    ( git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to GitHub Pages"
      && git push -fq origin $GH_BRANCH > /dev/null )
