# Avoid ruby stuff
language: c
sudo: false

branches:
    only:
      - master

env:
  global:
    - INPUT_FILE=Slides.md
    - OUTPUT_FILE=index.html
    - GH_REPO=ivan-m/pandoc-slideshow
    - GH_BRANCH=gh-pages
    - secure: QmGB8ym6pHEjs7cgWOKKbfpjWVzc0DAx8vEa6itg/ehCRPR9CZv3LpNtSAIR2QWBeijXAe1fyRVNSYWrWMMCTFUAbwN8usc4w+/9QL/uRJnpiVKuzUaNL679j3VBIjE4/214WvsGQINQvs/N6k8OFYDW9gsxfb5GjbPFaxVnE1C6kpnO7igmIte2/41QB0rv1XuaHNNI2NfGLX+/lJ3H/hba0JcFLiJtoDlCOV/RTAZ2Ikk9t1e86yFGSefZLh/58O/tfXY8EslaUnirp4c2QFpee93a4HCecgTcJ4XnJSR8Ew7loQAetKeuz9uYomIba2Lk34y3uHF4RFmpdylkp7TrUvdIgh/XP/ON6zGykJWoF3RSwZYhYpe49G5tRxzngCKJnZ9Gcssa1phN8xbhLv9Jl1/p+Aa745KiMuwkuMuuP7X63JQoRa7ldCcbzaDzfyh+AaCQLIbkCubjSsXJHps14v7a/aG70RH69YbDLhrwwik/Dd0dQGT/Hw15Z4qybmnjJqBBaA/YQBRXvD1ejoRZhotoB6EqdFMqbJa/JQrqIZuF8Uz9qpJm9WR7g2xmS3G8LkmRLDDfuFRafdv5bhUx3UINUq0kx6jJhrCtB2XBPjlemfy3AnNak5cO8h0NhDjpHUuBJIIyV4mbrxf6SM7n0xH1nZIX7OrX79/FYB4=

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

before-cache:
  # Don't cache the Hackage index
  - rm -rf $HOME/.cabal/packages/hackage.haskell.org

branches:
  only:
    - master

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-2.2
      - ghc-8.4.2

before_install:
  - export PATH=$HOME/.cabal/bin:$(printf "%s:" /opt/ghc/*/bin)$(printf "%s:" /opt/cabal/*/bin)$PATH
  - travis_retry cabal update
  - travis_retry cabal install -j pandoc

script:
  - ./runPandoc.hs "${INPUT_FILE}" "${OUTPUT_FILE}"
  - git config --global user.email "Travis CI"
  - git config --global user.name "travis-ci@travis.org"
  - git clone --quiet --branch=$GH_BRANCH https://${GH_TOKEN}@github.com/$GH_REPO travis-build > /dev/null
  - cd travis-build
  # In case there's more images, etc.
  - git rebase origin/shared-data
  - cp ../"${OUTPUT_FILE}" .
  - git add -f .
  - git diff --cached --exit-code ||
    ( git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to GitHub Pages"
      && git push -fq origin $GH_BRANCH > /dev/null )
